### ISSUE TITLE
Ability to create custom list of volunteers

### ISSUE THREAD

**Issue by dev-mansonthomas** [minutis-redcall/app#238]
To be discussed.

Ability to create custom lists, manually maintained.

Ex: sous ensemble des cadres de l'UL

To be able to sent sms to this custom list.

**Comment by ninsuo** [comment]
Similar to https://github.com/redcall-io/app/issues/191 
But indeed a list integrated in the UX would be easier to create

**Comment by ninsuo** [comment]
Similar to #191

**Comment by dev-mansonthomas** [comment]
At DT Level : 

Each UL should be able to request change to the list.

The idea is to mimic the functionality of this google sheet: 
https://docs.google.com/spreadsheets/d/1ap9X1zw4Hld3rxIc63dVjpe3C0bcorOB8cFL255vO90/edit#gid=0

**Comment by ninsuo** [comment]
close in favor of #640
