### ISSUE TITLE
Création de déclenchement: audience par nomination pegass pour les Multi Structure (DT...)

### ISSUE THREAD

**Issue by dev-mansonthomas** [minutis-redcall/app#289]
Audience : 

En plus des compétences secouristes / actions sociales, il faudrait pouvoir ajouter les roles suivants :

 - Si on a un profil multi structure (par exemple DT)
 - Une liste fonction cadre. 
    - _Option future :_ Cette liste doit être customisable par structure. En effet, entre DT, les fonctionnement peuvent être différent.

Dans un premier temps, on peut figer la liste à celle ci : 
- DLUS
- DLUS Mission de Secours
- DLUS Urgence
- DLAS
- Membre EDIR/ETIR

et en fonction des retours terrain, mettre en place la customisation.
Mais du coup, tu peux prévoir dans ton code, cette potentielle custo, pour rendre plus facile l'implémentation si on la fait.

**Comment by ninsuo** [comment]
About "Une liste fonction cadre."
What is / are the Pegass fields I should look at in order to have that info?

**Comment by ninsuo** [comment]
Looks like a dup of #238 ?

**Comment by dev-mansonthomas** [comment]
> About "Une liste fonction cadre."
> What is / are the Pegass fields I should look at in order to have that info?
La liste des nominations bénévoles, et on inclus celles la : 
DLUS
DLUS Mission de Secours
DLUS Urgence
DLAS

**Comment by ninsuo** [comment]
Désormais faisable avec #491 
La liste des badges est configurable ici: https://rcl.re/admin/badges
