### ISSUE TITLE
Volunteer management : search by phone

### ISSUE THREAD

**Issue by dev-mansonthomas** [minutis-redcall/app#416]
During a trigger, a lot of people are calling you and you don't have them in your phone.
Being able to search by phone number would be usefull

**Comment by ninsuo** [comment]
Can you clarify? 

It is already the case, but I suspect that you are looking for 06XXX instead of 336XXX.
I18n isn't quite well managed yet.

```
    private function addSearchCriteria(QueryBuilder $qb, string $criteria)
    {
        $qb
            ->andWhere(
                $qb->expr()->orX(
                    'v.nivol LIKE :criteria',
                    'v.firstName LIKE :criteria',
                    'v.lastName LIKE :criteria',
                    'v.phoneNumber LIKE :criteria',
                    'v.email LIKE :criteria',
                    'CONCAT(v.firstName, \' \', v.lastName) LIKE :criteria',
                    'CONCAT(v.lastName, \' \', v.firstName) LIKE :criteria'
                )
            )
            ->setParameter('criteria', sprintf('%%%s%%', $criteria));
    }
```

**Comment by dev-mansonthomas** [comment]
Ok, maybe you can update the criteria for the phone then : 

remove the + if it's in the user input.
replace the leading 0 by 33 if it's not 33

I was able to look for myself successfully with 336XXXX
