### ISSUE TITLE
Create a Trigger, Paste Nivols : Nivol with leading 0 are no longer recognized

### ISSUE THREAD

**Issue by dev-mansonthomas** [minutis-redcall/app#503]
If I create a trigger and paste a list of nivol, the nivol with leading 0 (0000XXXXX) are no longer recognize.
The leading 0 should be removed before searching for volunteers.

It's also the case in volunteer search
https://redcall.minutis.croix-rouge.fr/management/volunteers

**Comment by ninsuo** [comment]
fixed
