### ISSUE TITLE
When a RedCall user is disabled, he still appears in the list of users, which is confusing for other users

### ISSUE THREAD

**Issue by dev-mansonthomas** [minutis-redcall/app#520]
When a RedCall user is disabled (Utilisateur autorisé unchecked), 
he still appears in the list of users (with the RedCall icon next to his name), which is confusing for other users.

What's the difference between a disabled user and a deleted user ?

**Comment by ninsuo** [comment]
I don't really get the question.
- a disabled volunteer is deleted from pegass
- a non-triggerable volunteer don't want to be triggered
- there are no deleted volunteers, only anonymized ones

**Comment by dev-mansonthomas** [comment]
talking about users, not volunteers.

What are the difference betweend the 3rd and last option

[image: image.png]
