### ISSUE TITLE
Change ordering of messages when sending triggers

### ISSUE THREAD

**Issue by ninsuo** [minutis-redcall/app#534]
It may take 15 mins for the last volunteer targeted by a trigger to receive the message.

We should order the list of volunteers to trigger by skills, so most skilled people will receive the message first:
- first CI, VPSP, PSE2, PSE1, VL
- then others

That "trigger priority" should be editable on the badge edition

**Comment by dev-mansonthomas** [comment]
Good Idea!
If we paste a custom list of nivol, they may need to be prioritize as well. 
As it's the custom list of local unit manager that will handle the response of the volunteers of their units.
