### ISSUE TITLE
API : refresh one volunteer's data from pegass

### ISSUE THREAD

**Issue by dev-mansonthomas** [minutis-redcall/app#572]
In my use case, I check if data provided by the RCQ Admin are correct. 
I check that the provided email is a redcross one and equal to the one in Pegass.

It's very likely that the Pegass info are not up to date and that it must be updated.
But I can't wait a month for the refresh to occur.

So I would need to be able to ask RedCall to refresh the user's data from Pegass, and then perform my check again.

new API required : refresh one volunteer's data from pegass

**Comment by ninsuo** [comment]
Added the following contract.

![Screenshot 2021-04-13 at 08 31 24](https://user-images.githubusercontent.com/4152132/114508206-64e69e80-9c34-11eb-93db-8664f863dcc6.png)

Example:

![Screenshot 2021-04-13 at 08 33 33](https://user-images.githubusercontent.com/4152132/114508220-67e18f00-9c34-11eb-8ba8-2e52cebc4918.png)

Result:

![Screenshot 2021-04-13 at 08 42 32](https://user-images.githubusercontent.com/4152132/114508226-6912bc00-9c34-11eb-82db-91918109a69e.png)

Be careful, the call is synchronous. Refreshing a structure can take up to 30 seconds.
