### ISSUE TITLE
Create EMAIL Trigger : using chrome builtin autocorrect delete the line instead of correcting the word

### ISSUE THREAD

**Issue by dev-mansonthomas** [minutis-redcall/app#573]
When creating an email trigger,
and using the chrome built in auto correct feature
the word, or sometime the lines gets deleted instead of the selected word being corrected.

Ex: Etrangeres is missing accent
![image](https://user-images.githubusercontent.com/5695269/114468983-9e93b700-9bec-11eb-9cb2-c12f43cb30f4.png)
right click to correct it: 
![image](https://user-images.githubusercontent.com/5695269/114469001-a5bac500-9bec-11eb-9427-1c088232984d.png)
Etrangere as disappeared : 
![image](https://user-images.githubusercontent.com/5695269/114469019-abb0a600-9bec-11eb-9f8f-3803680d9a24.png)

**Comment by ninsuo** [comment]
Seems to be a known Quill issue: https://github.com/quilljs/quill/issues/2096
