### ISSUE TITLE
Ajout d'une fonctionnalité : création de liste de déclenchement personnalisée

### ISSUE THREAD

**Issue by Bjennepin** [minutis-redcall/app#640]
Donner la possibilité aux utilisateurs de créer des **listes de déclenchement personnalisées**, où ils peuvent ajouter des personnes à déclencher indépendamment des fonctions et nominations présentes dans base contacts et PEGASS. Il faut ainsi pouvoir proposer une fonctionnalité permettant à l'utilisateur de créer une liste de personnes déclenchables, lui attribuer un nom et pouvoir la conserver sauvegarder pour pouvoir la déclencher à tout instant. Cette fonctionnalité est demandée car elle était le moyen de fonctionnement de GSA.
Il faut aussi que le support national puisse avoir la main sur ces listes, en cas de besoin

**Comment by ninsuo** [comment]
dup: https://github.com/minutis-redcall/app/issues/238
